FNS App Frontend
spheronFdn/fns pull request #10
Opened 2023-02-23 07:06 UTC by SingingApple

2023-02-23 08:00 UTC, rekpero requested changes
lgtm, just update the depedency

2023-02-24 07:14 UTC, rekpero requested changes

2023-02-24 07:14 UTC, rekpero commented on .yarnrc
> +yarn-path ".yarn/releases/yarn-1.19.0.cjs"
Can you remove this file?

2023-02-24 07:26 UTC, rekpero requested changes

2023-02-24 07:26 UTC, rekpero commented on packages/frontend/src/Routes.tsx
> +import { BrowserRouter, Routes, Route } from 'react-router-dom'
use hashrouting

2023-02-26 12:18 UTC, rekpero approved these changes

2023-02-26 12:54 UTC, L-tech approved these changes
LGTM

2023-02-26 12:59 UTC, merged