Update readme file
spheronFdn/fns pull request #33
Opened 2023-03-23 15:48 UTC by L-tech

2023-03-23 16:29 UTC, rekpero requested changes

2023-03-23 16:29 UTC, rekpero commented on README.md
> +FNSlib can be currently used on Filcecoin Mainnet & Filecoin Hyperspace testnet network.
```suggestion
FNSlib can be currently used on Filecoin Mainnet & Filecoin Hyperspace testnet network.
```

2023-03-24 09:04 UTC, rekpero approved these changes

2023-03-24 10:30 UTC, aayushmahapatra approved these changes

2023-03-24 11:15 UTC, merged