Readme Update
spheronFdn/fns pull request #35
Opened 2023-03-27 19:37 UTC by L-tech

https://github.com/spheronFdn/fns/issues/34

2023-03-28 04:59 UTC, aayushmahapatra approved these changes
lgtm

2023-03-29 06:07 UTC, rekpero requested changes
some changes needed in the doc

2023-03-29 06:07 UTC, rekpero commented on README.md
> +At the moment, FNSlib supports BTC, LTC, DOGE, and FIL, but we're always looking to add support for more major chains in the future. If you have a specific request for a coinType, head on over to our
```suggestion
At the moment, FNSlib supports BTC, LTC, DOGE, and native FIL, but we're always looking to add support for more major chains in the future. 

If you have a specific request for a coinType, head to our 💬 [discord channel](https://discord.com/invite/ahxuCtm) and let us know. We're always considering new ideas for subsequent updates. 🚀
```

2023-03-29 06:07 UTC, rekpero commented on README.md
> +const  contentHash  =  await FNSInstance.getContent('juan.fil')
Apart from this, show how to get the name from address using FNSLib and describe the flow of how to use it

2023-04-02 07:17 UTC, rekpero approved these changes

2023-04-02 14:01 UTC, aayushmahapatra approved these changes

2023-04-02 14:33 UTC, merged