Add Get/Set Text Record, Extend Domain Support
spheronFdn/fns pull request #41
Opened 2023-05-01 14:20 UTC by nitinshr135

Fixes SPH-1709 SPH-1711 SPH-1712 SPH-1713 SPH-1714 SPH-1718 SPH-1720 SPH-1721 SPH-1722 SPH-1723

2023-05-01 21:39 UTC, SingingApple requested changes
Let's have interfaces for all responses now if feasible

2023-05-11 06:29 UTC, abhinav-spheron requested changes

2023-05-11 06:29 UTC, abhinav-spheron commented on packages/frontend/src/components/InputField/edit-subdomain.tsx
> +      // handleSearch()
@nitinshr135 Check this

2023-05-11 06:29 UTC, abhinav-spheron commented on packages/frontend/src/components/InputField/edit-subdomain.tsx
> +  editSubdomainName: (e: any) => void
Add appropriate type

2023-05-11 06:42 UTC, nitinshr135 commented on packages/frontend/src/components/InputField/edit-subdomain.tsx
> +      // handleSearch()
Edit subdomain feature is not yet functional as it is not implemented from the package side.

2023-05-11 06:44 UTC, nitinshr135 commented on packages/frontend/src/components/InputField/edit-subdomain.tsx
> +      // handleSearch()
Edit subdomain feature is not yet functional as it is not implemented from the package side.

2023-05-11 06:52 UTC, abhinav-spheron approved these changes
LGTM

2023-05-11 06:52 UTC, abhinav-spheron commented on packages/frontend/src/components/InputField/edit-subdomain.tsx
> +      // handleSearch()
Okay, got it.

2023-05-11 15:53 UTC, SingingApple requested changes
A few changes

2023-05-12 10:38 UTC, rekpero requested changes
small change needed, otherwise lgtm

2023-05-12 12:49 UTC, nitinshr135 commented on packages/frontend/src/components/Modal/extend-modal.tsx
> +      const res: any = await renewNames(option.searchQuery, year, price)
the response is coming as 
![image](https://github.com/spheronFdn/fns/assets/36033958/c630c98d-7f9d-473f-807e-988dc552ce34)

and the promise if of type `{
    error: boolean;
    response: {
        base: BigNumber;
        premium: BigNumber;
    } | undefined;
} | {
    error: boolean;
    response: string;
}`

getting some or other error while resolving this

2023-05-12 12:49 UTC, nitinshr135 commented on packages/frontend/src/components/Modal/extend-modal.tsx
> +      const res: any = await renewNames(option.searchQuery, year, price)
cc @rekpero

2023-05-12 13:54 UTC, rekpero approved these changes

2023-05-12 15:11 UTC, nitinshr135 commented on packages/frontend/src/components/Modal/extend-modal.tsx
> +      const res: any = await renewNames(option.searchQuery, year, price)
yes can be done 
cc @rekpero

2023-05-12 15:12 UTC, SingingApple approved these changes

2023-05-12 15:18 UTC, merged